apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoairquality-pipeline
  labels:
    app: geoairquality-pipeline
    component: data-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geoairquality-pipeline
  template:
    metadata:
      labels:
        app: geoairquality-pipeline
        component: data-pipeline
    spec:
      containers:
      - name: pipeline
        image: geoairquality/pipeline:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: geoairquality-secrets
              key: database-url
        - name: DASK_SCHEDULER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: geoairquality-config
              key: dask-scheduler-address
        - name: DATA_SOURCE_URLS
          valueFrom:
            configMapKeyRef:
              name: geoairquality-config
              key: data-source-urls
        - name: PROCESSING_INTERVAL_MINUTES
          value: "15"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - name: data-storage
          mountPath: /app/data
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: pipeline-data-pvc
      - name: config
        configMap:
          name: geoairquality-config
      restartPolicy: Always
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: geoairquality-data-ingest
spec:
  schedule: "*/15 * * * *"  # Every 15 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: data-ingest
            image: geoairquality/pipeline:latest
            command: ["python", "ingest.py", "--mode", "scheduled"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: geoairquality-secrets
                  key: database-url
            - name: DATA_SOURCE_URLS
              valueFrom:
                configMapKeyRef:
                  name: geoairquality-config
                  key: data-source-urls
            resources:
              requests:
                memory: "2Gi"
                cpu: "1"
              limits:
                memory: "8Gi"
                cpu: "4"
            volumeMounts:
            - name: data-storage
              mountPath: /app/data
          volumes:
          - name: data-storage
            persistentVolumeClaim:
              claimName: pipeline-data-pvc
          restartPolicy: OnFailure
      backoffLimit: 3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd